### ISSUE TITLE
Research GUI and Backend Implement 

### ISSUE THREAD

**Issue by skywalkerRex** [CMPE195-Group-28-Auto-Delivery-Robot/Auto_Deli_Robot#5]
Research about how we can build a web base Control Interface for Robot

**Comment by RuixiangHuang** [comment]
youtube.com/watch?v=fJDwgOJPRJE

**Comment by Hydraero** [comment]
https://medium.com/husarion-blog/bootstrap-4-ros-creating-a-web-ui-for-your-robot-9a77a8e373f9

**Comment by Hydraero** [comment]
Other Option: 
https://msadowski.github.io/ros-web-tutorial-pt1/
rosbridge server/websocket
+ 
roslibjs
